version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: application-database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Application123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - database_data:/var/opt/mssql
    networks:
      - application-network

  api:
    build:
      context: .
      dockerfile: src/PimFlow.Server/Dockerfile
    container_name: application-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__Provider=SqlServer
      - Database__ConnectionString=Server=database;Database=ApplicationDb;User Id=sa;Password=Application123!;TrustServerCertificate=true
      - Application__Name=PimFlow
      - Application__Version=1.0.0
      - Features__EnableSwagger=true
    ports:
      - "7000:80"
      - "7001:443"
    depends_on:
      - database
    networks:
      - application-network

  taskflow-client:
    build:
      context: .
      dockerfile: src/TaskFlow.Client/Dockerfile
    container_name: taskflow-client
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - taskflow-api
    networks:
      - taskflow-network

volumes:
  database_data:

networks:
  application-network:
    driver: bridge
