name: .NET Build and Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish Server
      run: dotnet publish src/TaskFlow.Server/TaskFlow.Server.csproj -c Release -o ./publish/server
      
    - name: Publish Client
      run: dotnet publish src/TaskFlow.Client/TaskFlow.Client.csproj -c Release -o ./publish/client
      
    - name: Upload Server Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: server-artifacts
        path: ./publish/server
        
    - name: Upload Client Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: client-artifacts
        path: ./publish/client
